import {useCallback,useEffect,useState} from 'react';

import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {useTranslation} from '@/i18n/useI18n';
import {openSubscription} from '@/lib/subscription';
import type {AgentQuota} from '@/lib/tochatModels';
import {cloudFetch} from '@/utils/modelSync';
type Card={id:string;issued_at:number;expires_at:number;used_at:number|null;status:'available'|'used'|'expired'};
type QuotaOverview=AgentQuota&{availableCards:number;cards:Card[];history:{id:string;card_id:string|null;created_at:number}[];serverTime:number};
export function QuotaSection(){
 const {t,i18n}=useTranslation();const[data,setData]=useState<QuotaOverview|null>(null),[tab,setTab]=useState<'available'|'history'>('available'),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null),[note,setNote]=useState('');
 const refresh=useCallback(async()=>{try{const response=await cloudFetch('/quota/overview',{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(t('subscription.unavailable'));setData(await response.json());setError('');}catch(e){setError((e as Error).message);}},[t]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);return()=>window.clearInterval(timer);},[refresh]);
 const date=(value:number|string)=>new Intl.DateTimeFormat(i18n.language.replace(/-Neko$/i,''),{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
 async function consumeCard(id:string){if(busy)return;setBusy(id);setError('');setNote('');try{const response=await cloudFetch('/quota/cards/use',{method:'POST',body:JSON.stringify({cardId:id})});const body=await response.json();if(!response.ok)throw Error(t(body.code==='busy'?'quotaSettings.busy':body.code==='subscription_required'?'subscription.none':body.code==='card_unavailable'?'quotaSettings.expired':'subscription.unavailable'));setNote(t('quotaSettings.resetSuccess'));window.dispatchEvent(new Event('tora-subscription-changed'));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 const available=data?.cards.filter(card=>card.status==='available')||[];
 return <div className="max-w-4xl space-y-10 pb-8"><h2 className="text-3xl font-semibold tracking-tight">{t('quotaSettings.usage')}</h2>
 <section className="space-y-3"><h3 className="font-semibold">{t('quotaSettings.currentPlan')}</h3><div className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-card px-5 py-4"><div><p className="font-medium">{data?.subscription?.name||t('subscription.none')}</p>{data?.subscription&&<p className="mt-1 text-sm text-muted-foreground">{t('subscription.expires',{time:date(data.subscription.expiresAt)})}</p>}</div><Button variant="secondary" onClick={openSubscription}>{t('quotaSettings.viewPlans')}</Button></div></section>
 <section className="space-y-3"><h3 className="font-semibold">{t('quotaSettings.allowance')}</h3><p className="text-sm leading-6 text-muted-foreground">{t('subscription.shared')} {t('subscription.chatFree')}</p>{data?.windows.map(window=><div key={window.key} className="space-y-3 rounded-2xl border border-border bg-card px-5 py-4"><p className="text-sm font-medium">{t(`subscription.${window.key}`)}</p><div className="flex flex-wrap items-center justify-between gap-2 text-sm text-muted-foreground"><span>{window.resetAt?t('subscription.nextRelease',{time:date(window.resetAt)}):'—'}</span><span className="tabular-nums">{t('subscription.remaining')} {window.remainingPercent.toFixed(1)}%</span></div><Progress value={window.remainingPercent} className="h-2 rounded-full [&_[data-slot=progress-indicator]]:rounded-full"/></div>)}</section>
 <section className="space-y-3"><h3 className="font-semibold">{t('quotaSettings.cards')}</h3><p className="text-sm text-muted-foreground">{t('quotaSettings.cardsInfo')}</p><div className="rounded-2xl border border-border bg-card px-5 py-4"><div className="mb-3 flex gap-1 border-b border-border pb-3">{(['available','history'] as const).map(value=><Button key={value} variant={tab===value?'secondary':'ghost'} size="sm" aria-pressed={tab===value} onClick={()=>setTab(value)}>{t(`quotaSettings.${value}`)}{value==='available'?' '+(data?.availableCards??available.length):''}</Button>)}</div>{tab==='available'?available.length?available.map(card=><div key={card.id} className="flex items-center justify-between gap-3 border-b border-border py-3 last:border-0"><div><p className="text-sm font-medium">{t('quotaSettings.cards')}</p><p className="mt-1 text-xs text-muted-foreground">{t('subscription.expires',{time:date(card.expires_at)})}</p></div><Button variant="secondary" disabled={!!busy||!data?.subscription} onClick={()=>void consumeCard(card.id)}>{t('quotaSettings.use')}</Button></div>):<p className="py-4 text-sm text-muted-foreground">{t('quotaSettings.noCards')}</p>:<div className="space-y-3">{data?.history.map(event=><div key={event.id} className="flex justify-between gap-3 text-sm"><span>{t('quotaSettings.resetSuccess')}</span><time className="text-muted-foreground">{date(event.created_at)}</time></div>)}{data?.cards.filter(card=>card.status==='expired').map(card=><div key={card.id} className="flex justify-between gap-3 text-sm"><span>{t('quotaSettings.expired')}</span><time className="text-muted-foreground">{date(card.expires_at)}</time></div>)}</div>}</div></section>
 {note&&<p role="status" className="text-sm text-muted-foreground">{note}</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button variant="ghost" size="sm" onClick={()=>void refresh()}>{t('applicationModes.retry')}</Button></div>;
}
